### ISSUE TITLE
An error on open server

### ISSUE THREAD

**Issue by MtnBiker** [Schwad/chat_gpt_error_handler#1]
```
 An error occurred while communicating with GPT:
undefined method `map' for nil:NilClass
~/.gem/ruby/3.2.0/gems/chat_gpt_error_handler-0.1.2/lib/chat_gpt_error_handler/error_handler.rb:46:in `send_to_gpt'
~/.gem/ruby/3.2.0/gems/chat_gpt_error_handler-0.1.2/lib/chat_gpt_error_handler/error_handler.rb:17:in `rescue in call'
~/.gem/ruby/3.2.0/gems/chat_gpt_error_handler-0.1.2/lib/chat_gpt_error_handler/error_handler.rb:13:in `call'

```
Using chruby for ruby versioning. Rails 7

Thanks, this looks like it will be helpful

**Comment by Schwad** [comment]
The responses come back in multiple different states and possibly types; I don't know if I've mapped them all out right. However, it would be nice to handle anything.

**Comment by Schwad** [comment]
I guess we could fix this to handle the nilcase though

**Comment by a5-stable** [comment]
I encountered the same issue, and in my case, it seems that my quota is running out.

```
{"error"=>                                
  {"message"=>"You exceeded your current quota, please check your plan and billing details.",
   "type"=>"insufficient_quota",          
   "param"=>nil,                          
   "code"=>nil}
}
```

**Comment by Schwad** [comment]
Yes you should check your open ai account on that one @a5-stable 

it might be nice to intercept this message and basically say that but a lot louder

**Comment by Schwad** [comment]
I'd say this is a different issue though!
